'use client'
import type { Metadata } from 'next'
import NavBar from '@/components/NavBar'
import MiniNavBar from '@/components/MiniNavBar'

export const metadata: Metadata = {
  title: 'Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <MiniNavBar />
      <NavBar />
      <div className="container mx-auto">{children}</div>
    </>
  )
}
